### ISSUE TITLE
Square Footage

### ISSUE THREAD

**Issue by enriquemoeller** [onshore-jousts/joust-1#8]
Should Square Footage entered by the user be divided by the number of rooms? Or is the square footage inputted by the user intended to represent the size of each room? I'm wondering because if we divide by the number of rooms, we are assuming all rooms are the same size. What do you think?

**Comment by nixondanielj** [comment]
The square footage input is representative of the total square footage to cover, e.g., 3 rooms of areas [3, 7, 20] would be represented by a 3 for the room count input and a 30 for the sqft input. 

For our purposes, you may assume that carpet may be trimmed and recombined to fit any individual room. That is to say, any combination of carpet rolls purchased which cover more than 30 square feet may be assumed to be sufficient to complete the job.

**Comment by enriquemoeller** [comment]
Does that mean that the number of rooms is unnecessary input, in terms of calculation, since all that matters is that the rolls add up to at least the total square footage?

**Comment by enriquemoeller** [comment]
Oh wait, nevermind. I see where it comes in later for labor... Thanks!
